apiVersion: v1
kind: Service
metadata:
  name: codeserver
  namespace: codeserver
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "codeserver"
spec:
  type: LoadBalancer
  selector:
    app: codeserver
  ports:
    - port: 8080
