global:
  domain: eu2.coralogix.com
  clusterName: duloc
  defaultApplicationName: duloc
  defaultSubsystemName: duloc
  collectionInterval: 120s
opentelemetry-agent:
  enabled: true
  mode: daemonset
  # Disable the AWS EC2 probing, we're not on AWS. Without this, the probes
  # fail and the deployment fails.
  # Needs to be set per-subhcart
  provider: on-prem
  presets:
    spanMetrics:
      enabled: false
    profilesCollection:
      enabled: false
    profilesK8sAttributes:
      enabled: false
    jaegerReceiver:
      enabled: false
    zipkinReceiver:
      enabled: false
  startupProbe:
    failureThreshold: 30
    httpGet:
      path: /
      port: 13133
    periodSeconds: 10
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
opentelemetry-cluster-collector:
  enabled: true
  mode: deployment
  # Same disabling of AWS stuff as above
  provider: on-prem
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
# Remember to redefined CORALOGIX_PRIVATE_KEY if we need to put this in
#  extraEnvs:
#    - name: GOGC
#      value: "400"
