apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  namespace: frigate
data:
  config.yml: |
    logger:
        logs:
          frigate.record.maintainer: debug

    mqtt:
        enabled: false
        host: "{FRIGATE_MQTT_HOST}"
        user: "{FRIGATE_MQTT_USER}"
        password: "{FRIGATE_MQTT_PASSWORD}"
    detectors:
        coral:
            type: edgetpu
            device: usb
    cameras:
        front:
            ffmpeg:
                inputs:
                    - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.0.193/Streaming/channels/101
                      roles:
                        - record
                    - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.0.193/Streaming/channels/102
                      roles:
                        - detect
            detect:
                width: 640
                height: 360
                fps: 3
                enabled: True
            motion:
                mask:
                - 640,235,362,219,172,190,0,172,0,0,640,0
            record:
                enabled: True
                retain:
                    days: 0.0417 # ~1 hour
                    mode: all
                events:
                  retain:
                    default: 14
                    mode: active_objects
            snapshots:
                enabled: True

        road:
            ffmpeg:
                inputs:
                    - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.0.192/Streaming/channels/101
                      roles:
                        - record
                    - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.0.192/Streaming/channels/102
                      roles:
                        - detect
            detect:
                width: 640
                height: 360
                fps: 3
                enabled: True
            motion:
                mask:
                - 640,235,362,219,172,190,0,172,0,0,640,0
            record:
                enabled: True
                retain:
                    days: 0.0417 # ~1 hour
                    mode: all
                events:
                  retain:
                    default: 14
                    mode: active_objects
            snapshots:
                enabled: True
        side:
            ffmpeg:
                inputs:
                    - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.0.190/Streaming/channels/101
                      roles:
                        - record
                    - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.0.190/Streaming/channels/102
                      roles:
                        - detect
            detect:
                width: 640
                height: 360
                fps: 3
                enabled: True
            record:
                enabled: True
                retain:
                    days: 0
                events:
                  retain:
                    default: 14
                    mode: active_objects
            snapshots:
                enabled: True
        rear:
            ffmpeg:
                inputs:
                    - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.0.191/Streaming/channels/101
                      roles:
                        - record
                    - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.0.191/Streaming/channels/102
                      roles:
                        - detect
            detect:
                width: 640
                height: 360
                fps: 3
                enabled: True
            record:
                enabled: True
                retain:
                    days: 0.0417 # ~1 hour
                    mode: all
                events:
                  retain:
                    default: 14
                    mode: active_objects
            snapshots:
                enabled: True
