coral:
    enabled: true
    hostPath: /dev/bus/usb

config: |
    logger:
        logs:
          frigate.record.maintainer: debug

    mqtt:
        enabled: false
    detectors:
        coral:
            type: edgetpu
            device: usb
    cameras:
        front:
            ffmpeg:
                inputs:
                    - path: rtsp://streamer:Stinkles@192.168.0.193/Streaming/channels/101
                      roles:
                        - record
                    - path: rtsp://streamer:Stinkles@192.168.0.193/Streaming/channels/102
                      roles:
                        - detect
            detect:
                width: 640
                height: 360
                fps: 3
                enabled: True
            motion:
                mask:
                - 640,235,362,219,172,190,0,172,0,0,640,0
            record:
                enabled: True
                retain:
                    days: 0
                events:
                  retain:
                    default: 14
                    mode: active_objects
            snapshots:
                enabled: True

        road:
            ffmpeg:
                inputs:
                    - path: rtsp://streamer:Stinkles@192.168.0.192/Streaming/channels/101
                      roles:
                        - record
                    - path: rtsp://streamer:Stinkles@192.168.0.192/Streaming/channels/102
                      roles:
                        - detect
            detect:
                width: 640
                height: 360
                fps: 3
                enabled: True
            motion:
                mask:
                - 640,235,362,219,172,190,0,172,0,0,640,0
            record:
                enabled: True
                retain:
                    days: 0
                events:
                  retain:
                    default: 14
                    mode: active_objects
            snapshots:
                enabled: True
        side:
            ffmpeg:
                inputs:
                    - path: rtsp://streamer:Stinkles@192.168.0.190/Streaming/channels/101
                      roles:
                        - record
                    - path: rtsp://streamer:Stinkles@192.168.0.190/Streaming/channels/102
                      roles:
                        - detect
            detect:
                width: 640
                height: 360
                fps: 3
                enabled: True
            record:
                enabled: True
                retain:
                    days: 0
                events:
                  retain:
                    default: 14
                    mode: active_objects
            snapshots:
                enabled: True
        rear:
            ffmpeg:
                inputs:
                    - path: rtsp://streamer:Stinkles@192.168.0.191/Streaming/channels/101
                      roles:
                        - record
                    - path: rtsp://streamer:Stinkles@192.168.0.191/Streaming/channels/102
                      roles:
                        - detect
            detect:
                width: 640
                height: 360
                fps: 3
                enabled: True
            record:
                enabled: True
                retain:
                    days: 0
                events:
                  retain:
                    default: 14
                    mode: active_objects
            snapshots:
                enabled: True
service:
  type: LoadBalancer
  port: 80
  loadBalancerIP: 192.168.0.204
  loadBalancerClass: tailscale

ingress:
    enabled: false

persistence:
    config:
        enabled: false
    media:
        enabled: true
        storageClass: longhorn
        size: 80Gi
